### ISSUE TITLE
`choco list` will become local only

### ISSUE THREAD

**Issue by alexchandel** [mwrock/boxstarter#103]
Per [choco#158](https://github.com/chocolatey/choco/issues/158), `choco list` may default to local only in the future. `choco search` should be used instead to list all packages, including those not installed.

**Comment by mwrock** [comment]
curious why you filed this here?

**Comment by ferventcoder** [comment]
Apparently @alexchandel believes that because you are using `choco list`, that you must be wanting to search for packages remotely instead of the locally installed packages.

See 
* https://github.com/chocolatey/chocolatey-cookbook/issues/44 (closed as invalid)
* https://github.com/chocolatey/puppet-chocolatey/issues/68 (closed as invalid)

**Comment by alexchandel** [comment]
Sorry, overly broad search parameters!
