### ISSUE TITLE
Install-WindowsUpdate command custom update servers

### ISSUE THREAD

**Issue by super23n** [mwrock/boxstarter#107]
Hi, ive already posted this question here: https://boxstarter.codeplex.com/discussions/644348 but wasn't sure if that board is still active.. it says there "now on GitHub", so here goes:

--PASTE--
Hello,
I've been using Boxstarter for some time now and been wondering if it's possible to use your own update servers to update Windows machines, when using the Install-WindowsUpdate command.

This parameter says:
GetUpdatesFromMS
If this switch is set, the default windows update server, if any, is bypassed and windows update requests go to the public Microsoft Windows update service.

How can I specify a custom update server? For example:
Install-WindowsUpdate http://myserver.lan

Thanks for your help!
--PASTE--

**Comment by mwrock** [comment]
I have not worked much at all with internal wus setups so I don't know how that all is setup. Its likely via group policy, but you would have to investigate. If `GetUpdatesFromMS` is specified, this tells the winduws update API to use the `ssWindowsUpdate` server selection instead of the default. See https://msdn.microsoft.com/en-us/library/windows/desktop/aa387280(v=vs.85).aspx
