### ISSUE TITLE
Invoke-Reboot - doesn't work 

### ISSUE THREAD

**Issue by it-praktyk** [mwrock/boxstarter#131]
The command Invoke-Reboot doesn't works as expected - the PowerShell window is closed only but after commenting the line 57 in the file Boxstarter.Bootstrapper\Invoke-Reboot.ps1 error is visible like on the attached screenshot.

![boxstarter_invoke-reboot-issue](https://cloud.githubusercontent.com/assets/4910261/11795941/d5eee31e-a2b9-11e5-9b0a-5b4b2b135eb7.jpg)

The error message is

```
You cannot call a method on a null-valued expression.
At <path>\Boxstarter\Boxstarter\Boxstarter.Bootstrapper\Invoke-Reboot.ps1:38 char:223
+ ... arter -RebootOk -NoPassword:`$$($Boxstarter.NoPassword.ToString())`""
+
    + CategoryInfo              : InvalideOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId  : InvokeMethodOnNull
```

**Comment by mwrock** [comment]
Thanks for reporting this! Will get this fixed tonight.

**Comment by mwrock** [comment]
I have a "fix" for this but its really just a warning. `Invoke-Reboot` should only be called from a package and not the commandline where it won't do anything. At least now it tells you that instead of closing the window. If you really do want to restart the machine from a commandline, use `Restart-Computer`.

Thanks!
