### ISSUE TITLE
Release 2.9.0 experiences file locking of pending chocolatey file

### ISSUE THREAD

**Issue by wilddev65** [mwrock/boxstarter#237]
Not sure what's changed in release 2.9.0 but my builds are now broken. First of all I wasn't getting Boxstarter.common. I expect that was due to Chocolatey not having yet received the package. Now all packages from Boxstarter are installing but the packages I'm installing after are failing. I've attached the package.ps1 I'm using.

The package (called install.txt) has;
$Boxstarter.RebootOk=$true # Allow reboots
$Boxstarter.AutoLogin=$true # Save my password securely and auto-login after a reboot

Write-BoxstarterMessage "Installing Windows Updates"
Install-WindowsUpdate -AcceptEula

choco feature enable -n=allowGlobalConfirmation

cinst googlechrome
cinst backinfo -s A:\
cinst notepadplusplus
cinst 7zip

choco feature disable -n=allowGlobalConfirmation

if(Test-PendingReboot){ Invoke-Reboot }

[package.ps1.txt](https://github.com/mwrock/boxstarter/files/871450/package.ps1.txt)

**Comment by mwrock** [comment]
2.9.0 just released a couple hours ago. The main change is the embedded chocolatey which was extremely old has been updated to the latest 0.10.4 beta. Can you be more specific about what has broken and include the boxstarter log file located at `$env:LocalAppData\boxstarter\boxstarter.log`?

**Comment by wilddev65** [comment]
It seems what breaks is the boxstarter_temp package build. This results in none of the packages above being installed, nor the Install-WindowsUpdate working. The log says chocolatey is having some sort of file locking or file access issue?

[boxstarter.log.txt](https://github.com/mwrock/boxstarter/files/872558/boxstarter.log.txt)

**Comment by flaviocdc** [comment]
I'm also not able to use boxstarter, but I'm experiencing this through ClickOnce (WebLaunch).
Can this issues be related? I'm trying to find some logs of the ClickOnce deployment, but I wasn't successful so far.

**Comment by mwrock** [comment]
do you mind opening up a separate issue @flaviocdc specific to your error and include what browser you are using? I'll rename this issue to make it clearer.

Also note that I just released 2.9.2 to address #238

**Comment by wilddev65** [comment]
Any progress on figuring out what's happening here?

**Comment by mwrock** [comment]
not yet. There were a couple other lower hanging bugs I needed to identify first. Hoping to get to this one tonight.

**Comment by mwrock** [comment]
ok I see what is happening here. Before installing a package, Chocolatey attempts to clean any files from "pending" package instralls (it did not do this in the version of chocolatey boxstarter used to embed). Because you have nested boxstarter packages - a package invoked with boxstarter that in turn invokes boxstarter again. Because both invocations generate a package from a script, they both create a package with the same name `temp_boxstarterpackage`. The second (inner) invocation fails because chocolatey has a lock on the package currently running.

I am fixing this by creating the on the fly packages with a random package name so that the nested invocations will generate different directories and eliminate contention.

I will release the fix along with a new beta version of chocolatey soon to be released that fixes another bug.

In the meantime, you can work around this by not calling `Install-BoxstarterPackage` inside the first boxstarter script and instead just directly execute that script.

**Comment by mwrock** [comment]
just released this fix in 2.9.5
