### ISSUE TITLE
WebLaunch seems to be a no-op

### ISSUE THREAD

**Issue by flaviocdc** [mwrock/boxstarter#239]
I'm trying to run Boxstarter through WebLaunch but as soon as the ClickOnce installer finishes, nothing happens (in the past a cmd.exe Window opened right way).

I'm running Windows Server 2016.
ClickOnce is being launched by Internet Explorer.

Let me know how can I find more details.
I'm doing my own investigation, but I couldn't find logs so far.

**Comment by mwrock** [comment]
thanks. Server 2016 is not in my test matrix but I have 2016 VMs handy and I'll have a look tonight.

**Comment by flaviocdc** [comment]
Installing boxstarter manually and then:
`BOXSTARTERSHELL -> Install-BoxstarterPackage -PackageName <url> `

This seems to be working (I'm seeing duplicate output, other than that, seems to be ok.)

![image](https://cloud.githubusercontent.com/assets/688926/24372547/2f38a884-12e3-11e7-902d-825d0e37aa4c.png)

**Comment by flaviocdc** [comment]
@mwrock let me know if I can provide any more info.

**Comment by mwrock** [comment]
I just so happened to need to spin up a 2016 vm and quickly did a `start http://boxstarter.org/package/nr/fiddler4` from a powershell console and the click once engaged without issue. One thing to note on 2016 and later win 10 versions is the "smart screen" flags boxstarter as malicious. I have no idea why that is. So when [prompted you need to click through the links to get it to install anyways.

Can you describe the behavior you are seeing? Or does it simply do nothing.

Also try turning off IE Enhanced securith. That may be a factor. I have it turned off on all 2012r2 and 2016 VMs.

**Comment by flaviocdc** [comment]
I ran _start http://boxstarter.org/package/nr/fiddler4_ and it didn't work.
I didn't even see the "smart screen" stuff. Just after ClickOnce instalation, nothing happens.

IE Enhanced Security is disabled.

Is there any way for me to try the older version of clickonce, just to verify if this is indeed a Boxstarter regression or if my IT dept pushed something to the machines and broke Boxstarter.

**Comment by mwrock** [comment]
unfortunately the click once app always gets latest and there is not a way around that right now. What happens if you try these:

1. run `start http://google.com` just curious if IE will be invoked at all.
2. Put the boxstarter url in a browser instead of a console

This might help zero in on the issue.

**Comment by flaviocdc** [comment]
1. `start google.com` works.
1. opening IE and putting the url on the browser still yields the same result.

**Comment by flcdrg** [comment]
Here's the warning after I clicked on `more info`. So it is picking up the code signing etc.

![image](https://cloud.githubusercontent.com/assets/384747/24383143/c4e20488-13a2-11e7-9ca7-eddabe52e89e.png)

Unfortunately I don't see a 'Report that this site does not contain threats' link

**Comment by flaviocdc** [comment]
@mwrock, is there anyway for me to run the WebLauncher without going through ClickOnce? I want to try that and see if I can repro the issue.

**Comment by mwrock** [comment]
Kind of. Have a look in `$env:LocalAppData\apps\2.0` There should be a `Data` directory and one or more randlomly named folders. Now there might be nothing here if the click once mechanism did not even get as far as downloading the bits which in your case is very likely. Anyways, if the bits were downloaded, you need to dive into each of these randomized folders until you find one that contains folders beginning with "boxs". One of these folders will contain a boxstarter.weblaunch.exe. So it will be interesting just to see if these folders exist on your machine.

One thing that would be interesting is to see if another click once app works. The problem is that I don't know of others off hand. Do you have other OSs in this same environment where the web launcher works?

One other "shot in the dark" to try is wiping your

**Comment by flaviocdc** [comment]
Sorry @mwrock, I wasn't able to look at this during this week. But i'll give this a shoot early next week and provide feedback.

**Comment by flaviocdc** [comment]
Hi @mwrock, this is definitely related to SmartScreen.
After some debugging here and there, I disabled SmartScreen and boxstarter worked.

I'm trying to find a way to debug why SmartScreen is blocking Boxstarter, but had no luck...
http://stackoverflow.com/questions/21735183/internet-explorer-smartscreen-filter-log-file points to Application Compat Toolkit, but there's no mention on **HOW** to use that to generate the event logs. 

Do you have any idea?

**Comment by mwrock** [comment]
I'm afraid I do not. I did some googling a while back to try and figure out how to get apps past it and what makes an app suspicious but did not turn anything up.

**Comment by flaviocdc** [comment]
Well, it seems that the problem is not happening anymore...
I'm pretty sure that it was something related to SmartScreen, but somehow it works now :)
So feel free to close this 👍
