### ISSUE TITLE
Package script not continuing after Windows Updates in Server 2016 Core

### ISSUE THREAD

**Issue by brettjacobson** [mwrock/boxstarter#266]
I'm using Install-WindowsUpdate in my boxstarter package, used during packer builds.  The packer build completes successfully if I'm installing the Desktop Experience, but if I'm installing Core, the build never finishes.  It doesn't seem like the windows update step inside Core is finishing correctly, and letting the system continue on to the next step in my "package.ps1" script.  If i comment out Install-WindowsUpdate, the Core build works fine, and it works fine if I let it install updates in the Desktop versions (both 2016 and 2012R2).
There is just something flakey with Core.
Any ideas?

here's a portion of my package.ps1
```
Install-WindowsUpdate -AcceptEula
if (Test-PendingReboot) { Invoke-Reboot }
Write-BoxstarterMessage 'Setting DNS servers...'
. a:\Set-DnsServers.ps1
```
I never see the "setting dns servers" and none of the other commands further down in the package.ps1 script

**Comment by mwrock** [comment]
Unfortunately Boxstarter does not work propperly with server core because after a reboot and login, it strts itself back up via a desktop menu item in the startup group. The core SKUs do not have these groups.

You might try adapting one of my 2016 templates in https://github.com/mwrock/packer-templates which use chef instead of boxstarter and don't suffer from this limitation.
