### ISSUE TITLE
How do I uninstall??

### ISSUE THREAD

**Issue by NovaViper** [mwrock/boxstarter#268]
I've been trying to figure out how can I uninstall this program.. but I have not seen anywhere on how to uninstall it.

**Comment by mwrock** [comment]
Sorry you are having trouble uninstalling. All of the boxstarter modules install to `$env:appdata/boxstarter`. Simply delete that folder and everything should be gone.

**Comment by NovaViper** [comment]
Thanks!

**Comment by Zeus64** [comment]
no it's not work ! left many mess in the system !

**Comment by pauby** [comment]
@Zeus64 See #336

**Comment by scrouthtv** [comment]
What does chocolatey / boxstarter create / change in Windows besides

 - the folders in ProgramData & AppData
 - disabling the UAC
 - disabling Windows Update

I didn't expect this to come installed with node but here I am..

**Comment by Garfonso** [comment]
How can it be that this issue is closed? Where is the uninstall functionality? This software creates a mess in my system and there is no way to uninstall it with all the stuff it throws at my system??? This is a serious issue and should be adressed ASAP. At least add documentation for how to get rid of this thing... your webpage only describes how to get even more mess onto the system. So this is clearly missing.

**Comment by pauby** [comment]
@Garfonso Please read the comments in the thread before posting?
