### ISSUE TITLE
v2.10.0 doesn't install in Windows-2012r2 Standard Core

### ISSUE THREAD

**Issue by jcoconnor** [mwrock/boxstarter#278]
Hi Matt,

Just noticed an issue with installing boxstarter on Windows-2012R2 Core.
Pinning back to the previous version of boxstarter (V2.9.26) appears to resolve the installation issue.

The start of the boxstarter installation output is: 
```
Installing the following packages:
Boxstarter
By installing you accept licenses for the packages.
Progress: Downloading BoxStarter.Common 2.10.0... 100%
Progress: Downloading boxstarter 2.10.0... 100%
Progress: Downloading BoxStarter.WinConfig 2.10.0... 100%
Progress: Downloading boxstarter.bootstrapper 2.10.0... 100%
Progress: Downloading boxstarter.chocolatey 2.10.0... 100%
Progress: Downloading Boxstarter.HyperV 2.10.0... 100%

BoxStarter.Common v2.10.0 - Possibly broken
boxstarter.common package files install completed. Performing other installation steps.
C:\ProgramData\Boxstarter
C:\ProgramData\Boxstarter\BuildPackages
Microsoft.PowerShell.Commands.Internal.Format.FormatStartData
Microsoft.PowerShell.Commands.Internal.Format.GroupStartData
Microsoft.PowerShell.Commands.Internal.Format.FormatEntryData
Microsoft.PowerShell.Commands.Internal.Format.GroupEndData
Microsoft.PowerShell.Commands.Internal.Format.FormatEndData
ERROR: You cannot call a method on a null-valued expression.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
The install of boxstarter.common was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\BoxStarter.Common\tools\chocolateyinstall.ps1'.
 See log for details.

BoxStarter.WinConfig v2.10.0 - Possibly broken
boxstarter.winconfig package files install completed. Performing other installation steps.
Microsoft.PowerShell.Commands.Internal.Format.FormatStartData
Microsoft.PowerShell.Commands.Internal.Format.GroupStartData
Microsoft.PowerShell.Commands.Internal.Format.FormatEntryData
Microsoft.PowerShell.Commands.Internal.Format.GroupEndData
Microsoft.PowerShell.Commands.Internal.Format.FormatEndData
ERROR: You cannot call a method on a null-valued expression.
The install of boxstarter.winconfig was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\BoxStarter.WinConfig\tools\chocolateyinstall.ps1'.
 See log for details.
```

Full Gist of the chocolatey log is available at: https://gist.github.com/jcoconnor/57799728984ef111333b845a3a05ea8e

John

**Comment by jspraul** [comment]
After the boxstarter setup/bootstrap faield, I ran the following command manually in an administrative command prompt and it appeared to work:

` cinst -y -verbose -force boxstarter`

### System Info
Windows 8 x64 (Powershell 3 instead of 4)
```
PS D:\> get-host

Name             : ConsoleHost
Version          : 3.0
InstanceId       : 589d7d4f-41ee-43a1-b717-03edf64e402c
UI               : System.Management.Automation.Internal.Host.InternalHostUserI
                   nterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

PS D:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.2.9200.17065
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2
```
### Steps
Chocolatey was updated to v0.10.7, including added to the path. 

`PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding..`

The exception handler in the chocolateyinstall.ps1 doesn't give enough detail to know exactly where the null reference is happening, even in the log. Can't this be changed to include line number + offset? 

Also, if the PATH change is what is breaking this, is there a way to stop the installation and tell chocolatey that it wasn't successfully installed?

```
ERROR: You cannot call a method on a null-valued expression.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
The install of boxstarter.common was NOT successful.
Error while running '[...]\lib\BoxStarter.Common\tools\chocolateyinstall.ps1'.
```
[20170725-boxstarter-2-10-bootstrap-first-run.txt](https://github.com/mwrock/boxstarter/files/1173835/20170725-boxstarter-2-10-bootstrap-first-run.txt)

Initial attempts to re-run the setup.bat for the bootstrapper showed that it was installed, 

```
Warnings:
 - boxstarter - Boxstarter v2.10.0 already installed.
 Use --force to reinstall, specify a version to install, or try upgrade.
```
[20170725-boxstarter-2-10-bootstrap-already-installed.txt](https://github.com/mwrock/boxstarter/files/1173848/20170725-boxstarter-2-10-bootstrap-already-installed.txt)

At this point I ran the chocolatey install manually as mentioned at the start of this comment

**Comment by jspraul** [comment]
I attempted to install v2.10.0 after successfully installing v2.9.26 (v2.9 doesn't work because only some packages are at 2.97), but the same error occurred. I decided to try to get something that was repeatable even on my own machine.

### Manual Uninstall
- Clear chocolatey log, then try to uninstall Boxstarter nicely
```
ren c:\programdata\chocolatey\logs\chocolatey.log "chocolatey %date:/=-% %time::=-%.log"
clist --local-only boxstarter
cuninst --all-versions Boxstarter.HyperV
cuninst --all-versions boxstarter.chocolatey
cuninst --all-versions boxstarter.bootstrapper
cuninst --all-versions BoxStarter.WinConfig
cuninst --all-versions BoxStarter.Common
cuninst --all-versions Boxstarter
```
- Remove C:\ProgramData\Boxstarter from the system PATH environment variable
- Remove %USERPROFILE%\AppData\Roaming\Boxstarter from the user PATH variable
- Open a new adminstrator command prompt, and delete all Boxstarter files (CAREFUL!)
```
rd /q /s c:\programdata\boxstarter
rd /q /s %userprofile%\appdata\roaming\boxstarter
for /f %i in ('dir c:\programdata\chocolatey\box*.* /a:d /s /b') do @if exist %i\. rd /q /s %i
del /q /s c:\programdata\chocolatey\box*.*
```
Verify boxstarter is gone:
```
set | findstr -i "boxstarter"
clist --local-only box
dir c:\programdata\box*.* /b /s
dir %userprofile%\appdata\roaming\boxstarter /b /s
```
### Install v2.10
```
..\boxstarter\setup.bat
..\boxstarter\setup.bat
..\boxstarter\setup.bat --force
cinst -y BoxStarter.Common -version 2.10


```

**Comment by mwrock** [comment]
There is a pending fix for this. I believe those running into this have no user scoped `PATH` (just the machine one).

**Comment by jspraul** [comment]
Yes, that was true in my case.

**Comment by mwrock** [comment]
Try 2.10.3 with the fix

**Comment by jspraul** [comment]
Looks good!

**Comment by jcoconnor** [comment]
Thats seems to fix it @mwrock 
Thanks

Also needed to remove this line as it is now showing an error:
```
Import-Module $env:appdata\boxstarter\boxstarter.chocolatey\boxstarter.chocolatey.psd1
```
