### ISSUE TITLE
Weaving PS Scripts into a Boxstarter package

### ISSUE THREAD

**Issue by KZeronimo** [mwrock/boxstarter#289]
I am weaving in a fair bit of native PS into [my Boxstarter script](https://gist.github.com/KZeronimo/3dd360bece3341a322335469a0a813ea) - it appears that if the PS scripts take too long that the Boxstarter process terminates

Is there a simple way to provide a timeout for these types of operations - I've taken a look at `Invoke-Task`

What is the correct way to weave this type of work in

**Comment by mwrock** [comment]
There are a couple places where boxstarter controls script timeouts. One is a hardcoded total timeout of 24 hours for the entire script to run. This overrides the default chocolatey timeout of 45 minutes. The other is in calls to `Invoke-FromTask` where boxstarter runs inside of a scheduled task. This typically only happens when running boxstarter on a remote machine and is limited to calls to `choco install`. The task is given a 1 hour timeout.

**Comment by KZeronimo** [comment]
Thank Matt - I was totally off on the root cause of the issue - sometime post VS 15.3 the VS command line installer kills PS during the install of Azure PS modules - a real drag
