### ISSUE TITLE
Install of 2.4.250 or 2.4.196 Hangs On PowerShell 2.0 / Chocolatey 0.9.9.4

### ISSUE THREAD

**Issue by DarwinJS** [mwrock/boxstarter#83]
Hello,
I think I have isolated this to happening on PowerShell 2.0 + Chocolatey 0.9.9.4.  PSH 4.0 on the same configuration seems to not have this problem.

Also, I have not had the problem before Chocolatey went to 0.9.9.4.

The install hangs right after "Copying the contents of 'C:\users\<userid>\appdata\local\temp\chocolatey\chocinstall\tools\ChocolateyInstall' to 'C:\programdata\Chocolateyinstall' .

I usually install boxstarter right after Chocolatey specifically so I can use Boxstarter to install .NET 4.5.1 and PowerShell 4.0 with reboot resiliency.  So it creates multiple manual steps and reboots to install PowerShell 4 before Boxstarter. 

This is happening on the standard Azure Server 2008 R2 SP1 image and on one I built myself for Win 8.1 Hyper-V

To make it worse, is seems chocolatey won't let me specify version 2.4.196 - it seems to ignore -version and just pulls 2.4.250.

So I downloaded all the 2.4.196 sources and pointed it locally - it hung at the same location.

So it may be a chocolatey 0.9.9.4 issue, but I have only experienced it with the boxstarter package so far.

Failing Configuration:
Win 8.1 Hyper-V AND Azure VM hosting:
Server 2008 R2 SP1
PowerShell 2
Chocolatey 0.9.9.4
BoxStarter 2.4.205

**Comment by timarenz** [comment]
Same here!

**Comment by issinoho** [comment]
I tracked this down to line 3 of `Check-Chocolatey.ps1` in `boxstarter.chocolatey` which explicitly checks for the existence of the following file,
```Powershell
$env:ChocolateyInstall\chocolateyinstall\helpers\chocolateyInstaller.psm1
```
If this file is missing then Boxstarter attempts to install Chcocolatey even though it is already installed.
The reason (I suspect) that it hangs is that at some point the script is looking for user confirmation on a file operation, which doesn't always bubble up to the command prompt (especially if using scripts).

The problem with all this is that since the 0.9.9 release of Chocolatey the file structure has changed and Boxstarter has not caught up yet.

As a workaround, I have created a (privately hosted) Chocolatey package which simply copies the contents of the pre-0.9.9 Chocolatey into `$env:ChocolateyInstall\chocolateyinstall'. I install this 'before' I install Boxstarter and this fixes the issue.

This is a benign operation as it new Chocolatey just ignores that folder now however the helper files allow Boxstarter to operate as normal.

Hope this helps until such time as Boxstarter catches up.

**Comment by mwrock** [comment]
Checking `$env:ChocolateyInstall\chocolateyinstall\helpers\chocolateyInstaller.psm1` is by design for now. Currently, boxstarter needs the older chcolatey powershell module to work. So if it is not there, even if 0.9.x is installed, boxstarter has a customized chocolatey installer that will go and get the older chocolatey and then only install the older powershell bits. In my testing, these two versions happily coexist and user calls to chocolatey on the commandline get handled by the new chocolatey but calls to chocolatey inside of a boxstarter context get handled by the older chocolatey. This is temporary until I get cycles to propperly support the new chocolatey which needs fundamental changes to both boxstarter and chocolatey to work.

I am going to try to reproduce this hang. Perhaps a more recent choco release is not playing nice. We'll see.

**Comment by issinoho** [comment]
@mwrock thanks for the update.

If it helps I can get this to hang 100% of the time so if you need me to do any specific tests or try any diagnostic versions then please PM me and I'd be happy to contribute some time.

**Comment by DarwinJS** [comment]
"...Currently, boxstarter needs the older chcolatey powershell module to work...."

Once I bust out of this hang and restart - my *relatively* complex server build works fine with the most recent version of Chocolatey and this version of BoxStarter.

Fyi,
D.

**Comment by issinoho** [comment]
@DarwinJS yes, it does seem to do pretty much all the required work before it hangs so, as you say, restarting the process will work on the 2nd try (mainly because that trigger file is now there so it doesn't repeat the guilty file copy operation).

Not much use with an automated build script though where the hang just blocks forever.

**Comment by mwrock** [comment]
Thanks for the help and info guys!

I'm in th midst of recovering my lab VMs (they got corrupted somehow on the plane ride back from ChefConf) and will hopefully get a repro or have more questions soon.

**Comment by mwrock** [comment]
I got my lab set back up yesterday and am able to reproduce this. I think I see the issue, there is a PS2 bug in the installer that causes it to prompt the user. The new choco wires up powershell in such a way that this is hidden and just hangs. I'm hoping to release a fix today.

Just an FYI. You can work around this by invoking boxstarter BEFORE installing chocolatey. You can do that by downloading `http://boxstarter.org/downloads/Boxstarter.2.4.205.zip`, extracting it and calling `setup.bat -force` in the root of the zip.

**Comment by mwrock** [comment]
This is released and I have validated that the hang no longer occurs on win 2k8r2. Thanks for reporting this!!

**Comment by issinoho** [comment]
Thanks for fixing this so promptly, @mwrock and for your hard work in general. I've tested on my system and all is good.

**Comment by DarwinJS** [comment]
Thanks much!

The first part of my build is publicly accessible, would it help if it was available for testing?

Also, Jeffrey Snover has indicated that he hopes WMF / PowerShell 5 can reach all the way back to Server 2008 R2 (SP1 I assume) and Windows 7.

That being the case - this use case of using Chocolatey and BoxStarter to bring a machine up to the proper baselines for .NET (4.5.1), PowerShell (4 or 5), Chocolatey, BoxStarter and DSC Resources may end up being quite common.  And this is exactly the automation where this was hanging for me.

D.
