### ISSUE TITLE
Old chocolatey in click-once installer

### ISSUE THREAD

**Issue by vorou** [mwrock/boxstarter#85]
I'm following [Launch from the web](http://boxstarter.org/WebLauncher).

Machine is fresh, so it installs chocolatey. Why it's installing old version (0.9.8.33)?
Also, I put `cup -y chocolatey` line in my boxstarter script and it's said "Nothing to update". Is there a way I could update chocolatey from script?

**Comment by mwrock** [comment]
Boxstarter intentionally (for now) installs 0.9.8.33 since it is not compatible with the latest chocolatey. Boxstarter can work with both versions installed but when calling `choco` from inside boxstarter, the older version is called. If `cup -y chocolatey` reports that it is running the latest version, you may want to check outside boxstarter what the version of chocolatey is and you may find that it is in fact the latest.
