### ISSUE TITLE
Boxstarter does not recogniz Chocolatey v0.9.9.5

### ISSUE THREAD

**Issue by htapal** [mwrock/boxstarter#89]
I setup a machine initially using a Boxstarter package script launched from the web.  I then upgraded chocolatey to the latest version.  Made some changes to the script and attempted to run again and it thinks chocolatey is no longer installed and so attempts to install again.

Is there a way around this?  Can boxstarter be upgraded to work with the latest version of Chocolatey?

**Comment by mwrock** [comment]
I apologize for this confusion. So currently, boxstarter does not work with the new chocolatey. There are some fundamental modifications that need to be made to boxstarter for it to work with the chocolatey rewrite. This is an important issue that I do plan to address. In the meantime, boxstarter will install the last powershell based version of chocolatey if it is not present. It does this using a modified installer so that if you have the newer version, the two will coexist peacfully and the older version will only be used by boxstarter while normal commandline calls to chocolatey will use the newer version.

This seems to be getting many folks confused. I'm inclined to add some messaging to that install to make it more clear what is happening.

**Comment by skyguy94** [comment]
This caught me by surprise. We're using an authenticated feed and with the new chocolatey we no longer needed the nuget credential workaround. Not a huge issue to fix (just keep the workaround for boxstarter). Does the issue stem from the chocolatey command interception?

**Comment by mwrock** [comment]
Thats correct. Boxstarter runs chocolaty in its own PS session and "monkey patches" a few of its functions. I have done some prototyping with using the choco.dll and it is possible to accomplish the same functionality but needs quite a bit of work.

**Comment by skyguy94** [comment]
Do you end up treating the new choco like an ABI?

**Comment by mwrock** [comment]
I just released v2.5.1 whose main focus was to further isolate the boxstarter specific chocolatey install from any user install and add extra messaging during the install and on each chocolatey package install to clarify that boxstarter uses its own version. Hope this helps.
