### ISSUE TITLE
Sysprepped boxstarter installation

### ISSUE THREAD

**Issue by timlie** [mwrock/boxstarter#92]
Here at our school we are trying to use Boxstarter.
I installed Boxstarter as admin in our default Win7 installation.
After the installation we sysprep this Win7 to use it for cloning purpose.
When deploying the image to computers, Boxstarter does not work anymore.

This is the error we get:

C:\Users\Administrator>boxstartershell

C:\Users\Administrator>powershell.exe -ExecutionPolicy bypass -NoE
xit -Command "&'C:\Users\Administrator\AppData\Roaming\Boxstarter\BoxstarterShel
l.ps1'"
The term 'C:\Users\Administrator\AppData\Roaming\Boxstarter\BoxstarterShell.ps1
' is not recognized as the name of a cmdlet, function, script file, or operable
 program. Check the spelling of the name, or if a path was included, verify tha
t the path is correct and try again.
At line:1 char:2
+ & <<<< 'C:\Users\Administrator\AppData\Roaming\Boxstarter\BoxstarterShell.ps1
'
    + CategoryInfo          : ObjectNotFound: (C:\Users\Admini...tarterShell.p
   s1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Thanks!

**Comment by mwrock** [comment]
When you sysprep the machine it deletes user specific accounts and directories. Since that's where the boxstarter bits are they get removed.

I'd consider adding the boxstarter install to your answer file so that it gets installed as part of windows os setup.

There is also an issue to not keep the boxstarter bits in user directories but instead install to programdata which will retain it through sysprep.
